### ISSUE TITLE
Experiment ToDo

### ISSUE THREAD

**Issue by behinger** [behinger/etcomp#1]
- [ ] make a copy of the experimental files, to keep both experiments in the current state. **Important** Don't duplicate the 'img' folder. Adapt the path in 'allgVar'
- [ ] Move the explanation text to own folder and repair paths in at least 'SpatStatMobileMem'  (and liklely more)
- [ ] change eyelink calibration to custom calibration targets (code e.g. from lilac chaser). The custom calibration targets need to be the pupillabs targets
- [ ] set auto-accept calibration/validation to off. We need to wait for pupillabs as well
- [ ] connect pupillabs with the experimental code to send trigger. Ask greta how to do it
- [ ] decide whether we need the actual memory recall task, or whether to just fake-question the subjects
- [ ] fix the timing in the experiment (memorizeImages & recallImages.m). t1 should not be getSecs, but t1 = Screen('flip',win).
- [ ] save the subject information after each trial (tic/toc -check to see how long it takes, but should be fine)
- [ ] Adapat prepScreens to our setup. this includes allgVar adaptations to our display. Also the isPc / old version thing can be removed 
- [ ] change font requirement in dispInstruction
- [ ] discuss whether we should use sound/beep for correct/false in memory task (as in previous study)
- [ ] remove crazy black + white background switches. They will mess up pupil responses and maybe make subjects move
- [ ] why is there dispInstructions 1 and 2? 1 is used in SpatStatMobileMem, 2 is used in 'memorizeImages.m (at break ')
- [ ]  remove the 'the experimenter will start the trial' and the 'loading image' screen. 
- [ ] translate all keycodes to actual keys. be sure to check whether unifykeyboard is called somewhere in the beginning
- [ ] What are the types in trialinfo.mem(x)? Just whether it is later repeated?
- [ ] what is the "calibration" step doing in 'memorizeImage'?
- [ ] why is the eyelink not automatically recalibration? Why are there only three points to recalib eyelink (or do I miss something => look at thesis again)

**Comment by behinger** [comment]
this is deprecated. we will not really copy the potsdam paradigm.

We should meet and discuss which part of the experimental structure of them to keep, i.e. how to structure the whole experiment - this will make programming a lot easier :)
