### ISSUE TITLE
Analysis TODO

### ISSUE THREAD

**Issue by k47ha** [behinger/etcomp#10]
- [ ] draw overview md
- [ ] extract **events** from **samples** --> nbp pupiltools

Tasks : Dataframe

Function:  find next fixation/saccade after msg   --> 2 lists (soll/ist)

- [ ] Large Grid :  Accuracy / 
                           Plot correlation of signals
- [ ]
