### ISSUE TITLE
Todo 05.10.2018

### ISSUE THREAD

**Issue by behinger** [behinger/etcomp#21]
- [x] consider deleting block 'parse trigger messages' in flow chart
- [x] different drift between the eye cameras?
- [x] Surface Intrinsic Camera undistortion
    => wontfix: Pupil labs does not have suppot for doing this offline right no
- [x] change all mean/medians to 20% winsorized mean
- [x] add SD to each fixation
- [x] I forgot what we said for the MS, adapt parameter?
    => even $\lambda$ of 15 does not help
- [x]  why the grid fixation durations show a bi-modal distribution
    => these are correction saccades that are missed by pupillab
- [x] why do we have very long fixations and more than 6 for the central fixation point in the large grid?
    => wrongly handeled element 50 trigger
- [x] fix the blink algorithm (forgot what we discussed, do we go for the always +100ms?, maybe we should just add 50ms on both ends)
     => added 100ms twice, fixed
- [x] analyse shake
- [x] analyse rotate
- [x] small grid: add some kind of single subject variability estimate (maybe lines?)

- [x] which monitor did we use: XL2430T or *XL2420T*?
   => we used the XL2420T

- [x] look at sales receipt of pupil labs glasses to find out 'name of version'
Thank you for your e-mail, the product id for this model is the pupil_w120_e120b, a high speed world camera and 120hz binocular eye cameras.
- [x] subject VP19 TILT condition has no Eyelink data
   => Subject misunderstood the task. removed from analysis (don't forget to add to paper!!)

**Comment by behinger** [comment]
**Why grid fixation duration bi-modal distribution**
![image](https://user-images.githubusercontent.com/10183650/46532944-2faea800-c8a3-11e8-8862-74b44f717303.png)

It seems its the last element, thus possibly related to the super long fixations we have in the grid?

**Comment by behinger** [comment]
More todos :-)

- [ ] Time between calibrations for small grid
- [ ] Time for each block
- [ ] 2D/3D calibration (internal only, or maybe one table for accuracy?)
- [ ] convert videos to h264 format (20gb to 2gb)
