### ISSUE TITLE
TODO 16.11.18   after rerunning data with updated functions

### ISSUE THREAD

**Issue by k47ha** [behinger/etcomp#28]
- [x] make history labels / commits on overleaf when adding (for comparison)
- [x] make new figures
- [x] make small grid statistics
- [x] program microsaccades again and try lambda of 5,8,15  (put it into the notebook)
- [x] put results about saccade amplitudes into the text
- [x] rewrite discussion
- [x] find replace * to the \SI
- [x]  Head movement: Labeling colors is missing for the different eye trackers. No explanation for different shades of grey.
- [x] be able to use PeerJ format
- [x] send draft to peter in PeerJ format on Wednesday 21.11
- [x] write test for 3d angle (accuracy)
- [x] put doi
- [x] rerun small grid statistics
- [x] remove whitespace around figures
- [x] renew screenshot (how do I make a screenshot in a high quality?)
- [x] renew black and grey offset plot from VP25  block2 with Helvetica font
- [x] put new smooth pursuit and freeview saccade amplitudes into the text
- [x] renew good raw signal after preprocessing with Helvetica font
- [x] adjust style of Figure 5 also content
- [x] Figure 9 (Results Freeviewing) is misssing which color is which eye tracker. Or we could mention that in caption?
- [x] put dondors in affiliation?
- [x] make data available at OSF (we also promised gif of grid task)
- [x] send Peter a Mail
But often, worse performance can be compensated by more trials or more subjects. But such "noise suppression" helps only with the square root of N.
A back-on-the-envelope calculation is: To compensate for the 40\% worse accuracy, one would need to record twice as many subjects (sqrt(2) $\approx$ 1.4) with Pupil Labs than with the EyeLink~1000 \citep[compare also to ]{wilming_measures_2011}.
change font in theme possible
eye tracking test battery
