### ISSUE TITLE
Questionnaire

### ISSUE THREAD

**Issue by k47ha** [behinger/etcomp#7]
Discuss which confounding factors should be part of the questionnaire:
- [ ] sex
- [ ] age
- [ ] Eye color
- [ ] Ask for explicit consent to use eye-camera videos
- [ ] drugs and sleep, 5h is enough
- [ ] psychological disorders, epilepsie
- [ ] visual acuity

- [ ] when (before/after experiment) should the questionnaire be presented?

**Comment by behinger** [comment]
[Einverständniserklärung_ehinger.docx](https://github.com/behinger/etcomp/files/1920932/Einverstandniserklarung_ehinger.docx)
[Anamnesebogen_ehinger.docx](https://github.com/behinger/etcomp/files/1920933/Anamnesebogen_ehinger.docx)
[Probandeninformation_ehinger.docx](https://github.com/behinger/etcomp/files/1920934/Probandeninformation_ehinger.docx)

We should modify those files to fit our experiment

**Comment by k47ha** [comment]
- [ ] Probandeninformation Beteiligte Institutionen
- [ ] separate additional questionare

**Comment by behinger** [comment]
**todo**
Visual Acuity Test
Eye Color Classifiaction

**Comment by behinger** [comment]
Done
http://www.openoptometry.com/Alpha/v4_0/OTC.html#lineSize=1.8&lineUnits=cm&distance=1&distanceUnits=meters&chartType=2&optoType=0&displayType=1&rowIndex=14&mirror=false&animate=false&crowd=false&nearFar=near&col1=#dedede&col2=#f10708&col3=#20e4fa&col4=#000000&mode3d=0
